In [1]:
! pip install numpy


# CREATING NUMPY ARRAYS

In [8]:
import numpy as np

In [3]:
array_one = np.array([0,1,3,5,7,9])
array_one

array([0, 1, 3, 5, 7, 9])

In [4]:
nums = [11,22,33,44,55,66,77,88,99]
array_two = np.array(nums)
array_two

array([11, 22, 33, 44, 55, 66, 77, 88, 99])

# NUMPY FUNCTIONS

###### creating array of ones with 2 rows & 3 columns where (2,3) are arguments passed for zeros function.




array_of_zeroes = np.zeros((2,3))  
array_of_zeroes

###### creating array of ones with 3 rows & 2 columns where (3,2) are arguments passed for zeros function.



array_of_ones = np.ones((3,2))
array_of_ones

###### So in above function each of the values are of type FLOAT so to avoid it....



array_of_ones = np.ones((3,2)) , dtype = (np.int32)
array_of_ones

###### it is an array of empty values but it takes values of ones



array_empty = np.empty((3,2))
array_empty

###### it is an array of 4 rows and columns with diagonal values to be one



array_eye = np.eye(4)
array_eye

###### arange if a function where array has a range, (2,24,2) are arguments for the function where 2 to 24 is the range with gap of 2(i.e last 2 of argument)



array_evens = np.arange(2,24,2)
array_evens

###### arange funtion does not only take "int" as arguments but it also takes floating point as values



array_float = np.arange(1,3,0.2)
array_float

###### it is an array formed with the help of 2 tuples



array_2D = np.array([(1,2,3),(4,5,6)])
array_2D

###### shape is used to check size of an array



array_2D.shape

###### it is an range of an array where 8 is an upper values and 0 is set as default values with default gap as 1



np.arange(8)

###### here reshape function is used to reshape array of range 8 to array with 2 rows and 4 colummns


#(here size of range needs to be accurate to fit in reshaped array or it will cause an error)


array_nd = np.arange(8).reshape(2,4)
array_nd

###### here this function is used to create array of ones but the arugment here means that array of ones need to be created just like array_nd but with values 1



array_ones = np.ones_like(array_nd)
array_ones

# PRINTING ARRAYS


###### printing one dimensional array



x = np.arange(8)
print(x)

###### printing two dimensional array



y = np.arange(16).reshape(4,4)
print(y)

###### printing three dimensional array



z = np.arange(36).reshape(3,4,3)
print(z)

###### printing large size array



np.arange(12100)

In [24]:
print(np.arange (12100).reshape(110,110))

[[    0     1     2 ...   107   108   109]
 [  110   111   112 ...   217   218   219]
 [  220   221   222 ...   327   328   329]
 ...
 [11770 11771 11772 ... 11877 11878 11879]
 [11880 11881 11882 ... 11987 11988 11989]
 [11990 11991 11992 ... 12097 12098 12099]]


In [25]:
np.set_printoptions(threshold = np.nan)
print(np.arange(12100).reshape(110,110))

ValueError: threshold must be non-NAN, try sys.maxsize for untruncated representation

In [26]:
print(np.arange(100).reshape(10,10))

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [27]:
np.set_printoptions(thershold = 50)
print(np.arange(100).reshape(10,10))

TypeError: set_printoptions() got an unexpected keyword argument 'thershold'

# NUMPY BASIC OPERATIONS


In [28]:
p = np.array([2,3,4])
q = np.array([4,5,6])

###### additon operation (element wise addition:2+4;3+5;4+6)

p + q

###### substraction operation (element wise substraction: 2-4;3-5;4-6)

p - q

In [33]:
print(p * q)
print(p % q)
print(p / q)   #other operations like multiply,mode, division

[ 8 15 24]
[2 3 4]
[0.5        0.6        0.66666667]


###### operation with scaler quantity



p % 2

In [35]:
p > 8

array([False, False, False])

In [36]:
p < 5

array([ True,  True,  True])

###### operations with two dimensional arrays

In [38]:
x = np.array([(1,2,3),(4,5,6)])
y = np.array([(1,3,5),(6,8,9)])

print('x:\n',x)
print('y:\n',y)

x:
 [[1 2 3]
 [4 5 6]]
y:
 [[1 3 5]
 [6 8 9]]


In [39]:
print(x + y)
print(x - y)
print(x * y)     
print(x % y)     #element wise operation is being done

[[ 2  5  8]
 [10 13 15]]
[[ 0 -1 -2]
 [-2 -3 -3]]
[[ 1  6 15]
 [24 40 54]]
[[0 2 3]
 [4 5 6]]


###### dot function for dot product

In [40]:
x.dot(y)

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [41]:
np.dot(x,y)

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

###### aggregate operations

###### for one dimesional array

In [42]:
fleet_milage = np.array([14130, 37234, 21892, 11479, 6890, 27981])

In [43]:
#sum of an array

fleet_milage.sum()

119606

In [44]:
#min value of an array

fleet_milage.min()

6890

In [45]:
#max value of an array

fleet_milage.max()

37234

In [46]:
#average value of an array(mean)

fleet_milage.mean()

19934.333333333332

###### for two dimensional array

In [47]:
num = np.arange(16).reshape(4,4)
num

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [48]:
#sum fucntion (it sums up all the values of the 2d array)

num.sum()

120

In [49]:
#sum fuction to sum up values of each of the column

num.sum(axis = 0)

array([24, 28, 32, 36])

In [50]:
#sum fuction to sum up values of each of the rows

num.sum(axis = 1)

array([ 6, 22, 38, 54])

In [51]:
#aggregate funnctions for 2D array

#min values of each row

num.min(axis = 1)

array([ 0,  4,  8, 12])

In [52]:
#mean for each of the row

num.mean(axis = 1)

array([ 1.5,  5.5,  9.5, 13.5])

# Universal Function


In [54]:
circle_radii = np.array([145, 120, 90, 60, 45, 30])


In [55]:
circle_diameter = 2 * circle_radii

circle_diameter

array([290, 240, 180, 120,  90,  60])

###### universal constant pi is used

In [57]:
circle_area = np.pi * circle_radii ** 2

circle_area   

array([66051.98554173, 45238.93421169, 25446.90049408, 11309.73355292,
        6361.72512352,  2827.43338823])

In [58]:
angle_degree = np.array([0, 30, 60, 90, 150, 180])

In [60]:
angle_radians = angle_degree * np.pi /180
angle_radians

array([0.        , 0.52359878, 1.04719755, 1.57079633, 2.61799388,
       3.14159265])

###### sine values function

In [64]:
print("sin values: ")
np.sin(angle_radians)

sin values: 


array([0.00000000e+00, 5.00000000e-01, 8.66025404e-01, 1.00000000e+00,
       5.00000000e-01, 1.22464680e-16])

###### cosine values function

In [65]:
print("cosine values: ")
np.cos(angle_radians)

cosine values: 


array([ 1.00000000e+00,  8.66025404e-01,  5.00000000e-01,  6.12323400e-17,
       -8.66025404e-01, -1.00000000e+00])

###### tan values function

In [66]:
print("tan value: ")
np.tan(angle_radians)

tan value: 


array([ 0.00000000e+00,  5.77350269e-01,  1.73205081e+00,  1.63312394e+16,
       -5.77350269e-01, -1.22464680e-16])

In [67]:
sine_values = np.sin(angle_radians)

###### inverse sine value function (arcsin)

In [71]:
arcsine_values = np.arcsin(sine_values)
arcsine_values

array([0.00000000e+00, 5.23598776e-01, 1.04719755e+00, 1.57079633e+00,
       5.23598776e-01, 1.22464680e-16])

###### exponential functions

In [72]:
x = np.arange(4,31,5)

x

array([ 4,  9, 14, 19, 24, 29])

In [74]:
expo = np.exp(x)

expo

array([5.45981500e+01, 8.10308393e+03, 1.20260428e+06, 1.78482301e+08,
       2.64891221e+10, 3.93133430e+12])

###### square root function

In [75]:
sqrt = np.sqrt(x)

sqrt

array([2.        , 3.        , 3.74165739, 4.35889894, 4.89897949,
       5.38516481])

###### median function

In [76]:
np.median(x)

16.5

# Indexing and Slicing

###### access element with index no

In [77]:
x = np.arange(10)**3

x

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [79]:
x[4]  #element on index 4

64

In [81]:
x[-4]   #element on index 4 from bottom side of array

216

###### slice

In [82]:
x[1:8]

array([  1,   8,  27,  64, 125, 216, 343], dtype=int32)

In [83]:
x[3:-3]

array([ 27,  64, 125, 216], dtype=int32)

In [84]:
x[ : 8]   #by default initial values is set 0 here

array([  0,   1,   8,  27,  64, 125, 216, 343], dtype=int32)

In [85]:
x[3: ]   #by default last values is set last on an array here

array([ 27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [86]:
x[ :10:2]  #here array starts with o to 10th index with increments of 2

array([  0,   8,  64, 216, 512], dtype=int32)

In [87]:
x[ : : -1] #this will show array in reverse order

array([729, 512, 343, 216, 125,  64,  27,   8,   1,   0], dtype=int32)

In [114]:
companies = np.array([['samsung','microsoft','IBM','spotify','flipkart'],
                      [ 1938, 1975, 2006, 2007],
                      [489000, 131000, 3000, 30000]])


C:\Users\adity\AppData\Local\Temp/ipykernel_12540/1881488489.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  companies = np.array([['samsung','microsoft','IBM','spotify','flipkart'],


In [116]:
companies

array([list(['samsung', 'microsoft', 'IBM', 'spotify', 'flipkart']),
       list([1938, 1975, 2006, 2007]),
       list([489000, 131000, 3000, 30000])], dtype=object)

###### access 1st row of an array

In [105]:
companies[0]

('samsung', 'microsoft', 'IBM', 'spotify', 'flipkart')

###### to get a data from a specific column need to specifiy multi dimensional array

In [107]:
companies[:, 2]

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

###### to access particular cell

In [99]:
companies[0, 2]

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

# Iterating over Arrays


In [117]:
x = np.arange(10)**3

x

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [118]:
for i in x :
    print(i)

0
1
8
27
64
125
216
343
512
729


In [119]:
companies = np.array([['samsung','microsoft','IBM','spotify','flipkart'],
                     [1938,1975,1911,2006,2007],
                     [489000,131000,380000,3000,30000]])

In [120]:
companies

array([['samsung', 'microsoft', 'IBM', 'spotify', 'flipkart'],
       ['1938', '1975', '1911', '2006', '2007'],
       ['489000', '131000', '380000', '3000', '30000']], dtype='<U11')

In [122]:
i = 0
for row in companies:
    print('Row',i,':',row)
    i += 1

Row 0 : ['samsung' 'microsoft' 'IBM' 'spotify' 'flipkart']
Row 1 : ['1938' '1975' '1911' '2006' '2007']
Row 2 : ['489000' '131000' '380000' '3000' '30000']


###### Flatten funtion (converts 2d arrays into single array)

In [123]:
companies.flatten() #row wise order

array(['samsung', 'microsoft', 'IBM', 'spotify', 'flipkart', '1938',
       '1975', '1911', '2006', '2007', '489000', '131000', '380000',
       '3000', '30000'], dtype='<U11')

In [125]:
for data in companies.flatten(order = 'F'):
 print (data)   #F stands for Fortran style ordering

samsung
1938
489000
microsoft
1975
131000
IBM
1911
380000
spotify
2006
3000
flipkart
2007
30000


###### nditer 

In [126]:
num = np.arange(16).reshape(4,4)

num

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [127]:
for i in np.nditer(num):
    print(i)   #for c style iterating

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


In [128]:
for i in np.nditer(num, order = 'F', flags = ['external_loop']):
    print(i)   #fortron style iterating

[ 0  4  8 12]
[ 1  5  9 13]
[ 2  6 10 14]
[ 3  7 11 15]


# Reshaping Arrays

In [129]:
tech_companies = np.array([('IBM','APPLE','INTEL','DELL','MICROSOFT'),
                          ('NEW YORK','CALIFORNIA','CALIFORNIA','TEXAS','WASHINGTON')])

tech_companies

array([['IBM', 'APPLE', 'INTEL', 'DELL', 'MICROSOFT'],
       ['NEW YORK', 'CALIFORNIA', 'CALIFORNIA', 'TEXAS', 'WASHINGTON']],
      dtype='<U10')

###### shape of an array

In [130]:
tech_companies.shape

(2, 5)

###### ravel function(reduces multi dimensioanl array to single directional array ,same as flatten function)

In [131]:
tech_companies.ravel()

array(['IBM', 'APPLE', 'INTEL', 'DELL', 'MICROSOFT', 'NEW YORK',
       'CALIFORNIA', 'CALIFORNIA', 'TEXAS', 'WASHINGTON'], dtype='<U10')

###### transpose (converts rows into columns and vice versa

In [132]:
tech_companies.T

array([['IBM', 'NEW YORK'],
       ['APPLE', 'CALIFORNIA'],
       ['INTEL', 'CALIFORNIA'],
       ['DELL', 'TEXAS'],
       ['MICROSOFT', 'WASHINGTON']], dtype='<U10')

###### flattening/raveling of a transpose array

In [133]:
tech_companies.T.ravel()

array(['IBM', 'NEW YORK', 'APPLE', 'CALIFORNIA', 'INTEL', 'CALIFORNIA',
       'DELL', 'TEXAS', 'MICROSOFT', 'WASHINGTON'], dtype='<U10')

###### reshaping of an array

In [135]:
tech_companies.shape

(2, 5)

In [136]:
tech_companies.reshape(5,2)

array([['IBM', 'APPLE'],
       ['INTEL', 'DELL'],
       ['MICROSOFT', 'NEW YORK'],
       ['CALIFORNIA', 'CALIFORNIA'],
       ['TEXAS', 'WASHINGTON']], dtype='<U10')

In [138]:
np.arange(18).reshape(3,6)  #3 rows and 6 columns

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

###### reshape operation with negative value

In [139]:
companies = np.array(['IBM','APPLE','INTEL',
                     'SONY','MICROSOFT','HP',
                     'HITACHI','PANASONIC'])

companies

array(['IBM', 'APPLE', 'INTEL', 'SONY', 'MICROSOFT', 'HP', 'HITACHI',
       'PANASONIC'], dtype='<U9')

In [140]:
companies.reshape(-1,4)

array([['IBM', 'APPLE', 'INTEL', 'SONY'],
       ['MICROSOFT', 'HP', 'HITACHI', 'PANASONIC']], dtype='<U9')

In [141]:
companies.reshape(4,-1)

array([['IBM', 'APPLE'],
       ['INTEL', 'SONY'],
       ['MICROSOFT', 'HP'],
       ['HITACHI', 'PANASONIC']], dtype='<U9')